name: Deploy Node Application
on:
  push:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secret.DOCKER.USERNAME }} -p ${{ secret.DOCKER.PASSWORD }}
      - name: Build Docker Image
        run: docker build -t lijojohnrbs/node_aws .
      - name: Publish Image to docker hug
        run: docker push lijojohnrbs/node_aw:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker push lijojohnrbs/node_aws:latest
      - name: Run Docker conainer
        run: docker run -d -p  8000-8000 --name nodejs-app-container -e MONGODB_URL=mongodb+srv://lijojohnrbs1:100100100@cluster0.zdgvzgf.mongodb.net/todo -e PORT=8000


